compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
num_processes: 4
mixed_precision: bf16
machine_rank: 0
num_machines: 1
main_process_ip: null
main_process_port: null
same_network: true
use_cpu: false
